import "./globals.css";
import 'bootstrap/dist/css/bootstrap.min.css';
import BootstrapClient from "./components/BootstrapClient";
import 'bootstrap-icons/font/bootstrap-icons.css';
import 'avalynx-alert/dist/css/avalynx-alert.css';
import 'avalynx-alert/dist/js/avalynx-alert.js';
import Navbar from "./components/navbar";
import { NextIntlClientProvider } from 'next-intl';
import { getLocale, getMessages } from 'next-intl/server';
import { getAvailableLangs } from '@/services/locale';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const locale = await getLocale();
  const messages = await getMessages();
  const locales = await getAvailableLangs();

  return (
    <html lang={locale} data-bs-theme="dark">
      <body>
        <NextIntlClientProvider messages={messages}>
          <Navbar locales={locales} />
          {children}
        </NextIntlClientProvider>
        <BootstrapClient />
      </body>
    </html>
  );
};